-
  id: date
  valueType: text
  valueUnit: date
  valueFormat: YYYY-MM-DD
  equivalents: Data
  isMeteo: false
-
  id: time
  valueType: text
  valueUnit: time
  valueFormat: HH:MM
  equivalents: Czas
  isMeteo: false
-
  id: airTemperature
  valueType: number
  valueUnit: celsius
  equivalents: Temperatura powietrza;Temperatura
-
  id: perceptibleTemperature
  valueType: number
  valueUnit: celsius
  equivalents: Temperatura odczuwalna
-
  id: soilTemperature
  valueType: number
  valueUnit: celsius
  equivalents: Temp. przy gruncie
-
  id: airHumidity
  valueType: number
  valueUnit: percent
  equivalents: Wilgotność powietrza;Wilgotność
-
  id: wettingOfLeaves
  valueType: number
  valueUnit: unknown
  equivalents: Zwilżenie liścia
-
  id: atmosphericPressure
  valueType: number
  valueUnit: hectopascal
  equivalents: Ciśnienie atmosferyczne;Ciśnienie
-
  id: barometricPressure
  valueType: number
  valueUnit: hectopascal
  equivalents: Ciśnienie barometryczne
-
  id: windSpeed
  valueType: number
  valueUnit: meter_per_second
  equivalents: Prędkość wiatru;Kierunek i prędkość wiatru
-
  id: windSpeedMax
  valueType: number
  valueUnit: meter_per_second
  equivalents: Maksymalna prędkość wiatru
-
  id: windDirectionAngle
  valueType: number
  valueUnit: angle
  equivalents: Kąt kierunku wiatru
-
  id: windDirection
  valueType: text
  valueUnit: direction
  equivalents: Kierunek wiatru
-
  id: windSpeedMedium
  valueType: number
  valueUnit: meter_per_second
  equivalents: Prędkość średnia
-
  id: uvRadiation
  valueType: number
  valueUnit: none
  equivalents: Promieniowanie UV;Promieniowanie UV (tylko w dzień)
-
  id: solarRadiation
  valueType: number
  valueUnit: watt_per_square_meter
  equivalents: Promieniowanie słoneczne;Promieniowanie słoneczne (tylko w dzień)
-
  id: dewPoint
  valueType: number
  valueUnit: celsius
  equivalents: Punkt rosy
-
  id: momentDrop
  valueType: number
  valueUnit: millimetre_per_hour
  equivalents: Opad chwilowy;Aktualny opad deszczu
-
  id: stormyDrop
  valueType: number
  valueUnit: millimetre
  equivalents: Opad burzowy
-
  id: dropDaily
  valueType: number
  valueUnit: millimetre
  equivalents: Opad;Dzisiejszy opad deszczu;Opad 24h
-
  id: dropMonthly
  valueType: number
  valueUnit: millimetre
  equivalents: Opad miesięczny
-
  id: dropYearly
  valueType: number
  valueUnit: millimetre
  equivalents: Opad roczny
-
  id: hail
  valueType: number
  valueUnit: hits_per_square_centimeter
  equivalents: Grad
-
  id: dropIntensity
  valueType: number
  valueUnit: millimetre_per_hour
  equivalents: Intensywność opadu
-
  id: hailIntensity
  valueType: number
  valueUnit: hits_per_square_centimeter_per_hour
  equivalents: Intensywność gradu
-
  id: tendency
  valueType: text
  valueUnit: none
  equivalents: Tendencja
-
  id: THW
  valueType: number
  valueUnit: celsiusz
  equivalents: Współczynnik THW
-
  id: heatIndex
  valueType: number
  valueUnit: celsiusz
  equivalents: Indeks ciepła